# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField(max_length=400)),
                ('sigra', models.CharField(max_length=128)),
                ('numero', models.CharField(max_length=128)),
                ('ano', models.CharField(max_length=128)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('data_de_fim', models.DateField(blank=True, null=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cpf', models.CharField(max_length=128)),
                ('mae', models.CharField(max_length=128)),
                ('pai', models.CharField(max_length=128)),
            ],
            bases=('eventos.pessoa',),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.PessoaFisica'),
        ),
    ]
